{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.svm import SVC\n",
    "\n",
    "from itertools import combinations, chain\n",
    "\n",
    "from sklearn.ensemble import StackingClassifier\n",
    "\n",
    "from sklearn.model_selection import GridSearchCV, RandomizedSearchCV\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "from sklearn.metrics.pairwise import distance_metrics\n",
    "from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, RocCurveDisplay, auc\n",
    "\n",
    "from joblib import dump\n",
    "from imblearn.over_sampling import SMOTE\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "data = pd.read_csv('../../../DATA/Concatination_of_ters/Without_Индекс стоимости жизни/classes.csv').dropna()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "X, y = data.drop('Средняя численность работников, включая внешних совместителей',\n",
    "                 axis=1), data['Средняя численность работников, включая внешних совместителей']\n",
    "X_balanced, y_balanced = SMOTE().fit_resample(X, y)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_balanced['Средняя численность работников, включая внешних совместителей'] = y_balanced\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "data_smoted = X_balanced"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train_smoted, X_test_smoted, y_train_smoted, y_test_smoted = train_test_split(data_smoted.drop('Средняя численность работников, включая внешних совместителей', axis=1),\n",
    "                                                    data_smoted['Средняя численность работников, включая внешних совместителей'], test_size=0.5, random_state=42)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.58304388        nan 0.49642857        nan        nan 0.62142574\n",
      " 0.49642857        nan 0.59837104 0.60572398        nan 0.60069094]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'weights': 'distance',\n",
       " 'p': 6,\n",
       " 'n_neighbors': 1,\n",
       " 'metric': 'l1',\n",
       " 'algorithm': 'brute'}"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "knn_optimal_n_neighbors_by_f1 = RandomizedSearchCV(KNeighborsClassifier(),\n",
    "                                                   {'n_neighbors': np.arange(1, 10, 2),\n",
    "                                                    'weights': ['uniform', 'distance'],\n",
    "                                                    'algorithm': ['ball_tree', 'kd_tree', 'brute'],\n",
    "                                                    'p': np.arange(1, 10, 1),\n",
    "                                                    'metric': list(distance_metrics().keys())\n",
    "                                                    },\n",
    "                                                   n_iter=12,\n",
    "                                                   n_jobs=4,\n",
    "                                                   scoring='f1',\n",
    "                                                   random_state=71\n",
    "                                                   ).fit(X_train_smoted, y_train_smoted)\n",
    "knn_optimal_n_neighbors_by_f1.best_params_\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.61111111        nan 0.54166667        nan        nan 0.61111111\n",
      " 0.54166667        nan 0.61111111 0.61111111        nan 0.63611111]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'weights': 'distance',\n",
       " 'p': 6,\n",
       " 'n_neighbors': 1,\n",
       " 'metric': 'l1',\n",
       " 'algorithm': 'brute'}"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "knn_optimal_n_neighbors_by_recall = RandomizedSearchCV(KNeighborsClassifier(),\n",
    "                                                   {'n_neighbors': np.arange(1, 10, 2),\n",
    "                                                    'weights': ['uniform', 'distance'],\n",
    "                                                    'algorithm': ['ball_tree', 'kd_tree', 'brute'],\n",
    "                                                    'p': np.arange(1, 10, 1),\n",
    "                                                    'metric': list(distance_metrics().keys())\n",
    "                                                    },\n",
    "                                                   n_iter=12,\n",
    "                                                   n_jobs=4,\n",
    "                                                   scoring='recall',\n",
    "                                                   random_state=71\n",
    "                                                   ).fit(X_train_smoted, y_train_smoted)\n",
    "knn_optimal_n_neighbors_by_f1.best_params_\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'C': 1.8,\n",
       " 'decision_function_shape': 'ovo',\n",
       " 'kernel': 'linear',\n",
       " 'probability': True}"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "svc_optimal = GridSearchCV(SVC(),\n",
    "                                       {'probability': [True, False],\n",
    "                                        'C': np.arange(1.8, 1.9, 0.01),\n",
    "                                        #   'tol': np.arange(0, 2e-3, 1e-4),\n",
    "                                        # 'degree': np.arange(0, 2, 1),\n",
    "                                        #   'gamma': ['scale'] + [*np.arange(0, 1, 0.1)],\n",
    "                                        # 'coef0': np.arange(0, 0.2, 0.1),\n",
    "                                        # 'shrinking': [True, False],\n",
    "                                        # 'break_ties': [True, False],\n",
    "                                        'decision_function_shape': ['ovo', 'ovr'],\n",
    "                                        'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},\n",
    "                                       n_jobs=6,\n",
    "                                       scoring='recall',\n",
    "                                       cv=3\n",
    "                                       ).fit(X_train_smoted, y_train_smoted)\n",
    "svc_optimal.best_params_\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Recall"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "6 fits failed out of a total of 9.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "3 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 660, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 227, in fit\n",
      "    self.stack_method_ = [\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 228, in <listcomp>\n",
      "    self._method_name(name, est, meth)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 157, in _method_name\n",
      "    raise ValueError(\n",
      "ValueError: Underlying estimator svc does not implement the method predict_proba.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "3 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 660, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 227, in fit\n",
      "    self.stack_method_ = [\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 228, in <listcomp>\n",
      "    self._method_name(name, est, meth)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 157, in _method_name\n",
      "    raise ValueError(\n",
      "ValueError: Underlying estimator knn_f1 does not implement the method decision_function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.56776557]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.58304388        nan 0.49642857        nan        nan 0.62142574\n",
      " 0.49642857        nan 0.59837104 0.60572398        nan 0.60069094]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.61111111        nan 0.54166667        nan        nan 0.61111111\n",
      " 0.54166667        nan 0.61111111 0.61111111        nan 0.63611111]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.62628205        nan 0.45631579        nan        nan 0.63743316\n",
      " 0.45631579        nan 0.59807692 0.61439394        nan 0.63141026]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.49809524        nan 0.4370696         nan        nan 0.53730769\n",
      " 0.35438561        nan 0.53142857 0.56              nan 0.49809524]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.50393162        nan 0.42470667        nan        nan 0.49752137\n",
      " 0.41591546        nan 0.48994561 0.48994561        nan 0.46837607]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.57260073        nan 0.3804995         nan        nan 0.64505495\n",
      " 0.3804995         nan 0.67619048 0.65714286        nan 0.59166667]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.62211999        nan 0.52431078        nan        nan 0.6679164\n",
      " 0.52431078        nan 0.66425339 0.6745098         nan 0.61333333]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.68571429        nan 0.51428571        nan        nan 0.68571429\n",
      " 0.51428571        nan 0.62857143 0.65714286        nan 0.68571429]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.49047619        nan 0.46190476        nan        nan 0.55238095\n",
      " 0.37619048        nan 0.51904762 0.55238095        nan 0.49047619]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.50952381        nan 0.47142857        nan        nan 0.50952381\n",
      " 0.47142857        nan 0.48095238 0.48095238        nan 0.47619048]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.58571429        nan 0.36666667        nan        nan 0.64285714\n",
      " 0.36666667        nan 0.7        0.67142857        nan 0.60952381]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.63809524        nan 0.58095238        nan        nan 0.7\n",
      " 0.58095238        nan 0.66666667 0.66666667        nan 0.6       ]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'stack_method': 'predict'}"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "stacking_classifie_optimall_params = GridSearchCV(StackingClassifier([('knn_f1', knn_optimal_n_neighbors_by_f1), \n",
    "                                                                      ('knn_recall', knn_optimal_n_neighbors_by_recall), \n",
    "                                                                      ('svc', svc_optimal)]),\n",
    "                                                  {'stack_method': ['predict_proba', 'decision_function', 'predict']},\n",
    "                                                  n_jobs=6,\n",
    "                                                  scoring='recall',\n",
    "                                                  cv=3\n",
    "                                                  ).fit(X_train_smoted, y_train_smoted)\n",
    "stacking_classifie_optimall_params.best_params_\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "y_predicted = stacking_classifie_optimall_params.predict(X_test_smoted)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[30 11]\n",
      " [14 33]]\n"
     ]
    }
   ],
   "source": [
    "print(confusion_matrix(y_test_smoted, y_predicted))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "              precision    recall  f1-score   support\n",
      "\n",
      "       False       0.68      0.73      0.71        41\n",
      "        True       0.75      0.70      0.73        47\n",
      "\n",
      "    accuracy                           0.72        88\n",
      "   macro avg       0.72      0.72      0.72        88\n",
      "weighted avg       0.72      0.72      0.72        88\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print(classification_report(y_test_smoted, y_predicted))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<sklearn.metrics._plot.roc_curve.RocCurveDisplay at 0x1e095fad9a0>"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYIAAAEGCAYAAABo25JHAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAAu0UlEQVR4nO3deXxU9fX/8ddJCCTshACyJyyCQCJLgihFQRRxAwVapW64VIpiv/1pBapUqCIuWFut2hYVcUFAETVVFDdAxQUCQoCwQ4Cwr2ENZDm/P2aSJiHLhOTOzWTO8/HIg7l37sy8L4E5cz9n7v2IqmKMMSZ4hbgdwBhjjLusEBhjTJCzQmCMMUHOCoExxgQ5KwTGGBPkqrkdoKyioqI0Ojra7RjGGBNQli1bdkBVGxV1X8AVgujoaJKSktyOYYwxAUVEthV3nw0NGWNMkLNCYIwxQc4KgTHGBDkrBMYYE+SsEBhjTJBzrBCIyDQR2Sciq4u5X0TkRRHZJCLJItLdqSzGGGOK5+QRwXRgYAn3Xw209/7cC/zLwSzGGGOK4VghUNVvgUMlbDIYeEs9fgLqi0hTp/IYY0wgOnUmmx82HeAfX21gza50R17DzRPKmgM78i2nedftLryhiNyL56iBVq1a+SWcMca44cjJMyxNPczS1EMs2XqI1TvTycpRRKBh7Rp0blavwl8zIM4sVtWpwFSA+Ph4m0nHGFNl7DpyKu9Nf2nqITbsPQ5A9dAQ4lrU43eXtqFndCTdWzegXkSYIxncLAQ7gZb5llt41xljTJWkqmzef5wlW//3iX/nkVMA1K5Rje6tGzDowmYkREdyYcv6hIeF+iWXm4UgERgtIrOAi4B0VT1rWMgYYwJVVnYOa3YdzXvTT9p2mEMnzgAQVbs6CdGR3P2rGHrGRNLxvDpUC3XnG/2OFQIRmQn0BaJEJA2YAIQBqOq/gXnANcAm4CRwp1NZjDHGH06dyeaX7YfzxviXbz/MyTPZALSKrEm/Do3pGdOAhOhIYqJqISIuJ/ZwrBCo6vBS7lfgfqde3xhjnFZSY7dDkzoM69GChOhIesZE0qRuuNtxixUQzWJjjKkMfGnsJkQ3oEfrSMcau06wQmCMMUWorI1dJ1ghMMYYAqex6wQrBMaYoHTqTDa/7DjM0q2B1dh1ghUCY0xQOHLyDEm5jd1UT2M3MzvwGrtOsEJgjKmS8jd2k1IPs37vMQDCQoW4FvW5+1dt6BkTeI1dJ1ghMMYEPF8au9df2JT46Ei6Bnhj1wlWCIwxASeYG7tOsEJgjKn0rLHrLCsExphKxxq7/mWFwBjjut3pp/LO1l261Rq7/maFwBjjV7mN3aWph1m61fOJP+2wp7Fbq3oo3Vs34Lq4piTEWGPXX6wQGGMc5Utj967e1th1kxUCY0yFssZu4LFCYIwpF18buwnRkZxXzxq7lZEVAmNMmfjc2G0VSb2a1tgNBFYIjDHF8jR2T3jf9K2xW1VZITDG5MnKziFl99G8T/xJqYc56G3sNqzlaeze2TuGntGRXNDUGrtVhRUCY4JY/sZu0rZDLN92mBP5Grt9OzQmIboBCTGRtLHGbpVlhcCYIJJ+MtMzzFNMY3eoNXaDkhUCY6owa+waX1ghMKaKsMauOVdWCIwJUNbYNRXFCoExASIjM5tfth/JG+O3xq6pKFYIjKmk0k9mkrTNM8SzdOshVllj1zjECoExlcSe9Iy8N/2lqYdYv/cYqtbYNc6zQmCMCwo0dr0/Ow4VbOxeG2uNXeMfVgiM8QNfGrsjLrHGrnGHFQJjHFBSY7dlZASXdWhEz+hIa+yaSsEKgTEVoLTG7pDuLUiIiaSnNXZNJWSFwJhzYI1dU5U4WghEZCDwAhAKvKaqTxe6vxXwJlDfu804VZ3nZCZjykpV2XLgRN7ZutbYNVWNY4VAREKBl4ErgTRgqYgkqmpKvs3GA++p6r9EpBMwD4h2KpMxvsjKzmHt7mN5n/iTth3iwHFr7Jqqy8kjgp7AJlXdAiAis4DBQP5CoEBd7+16wC4H8xhTpNIau5eeb41dU7U5WQiaAzvyLacBFxXaZiLwhYg8ANQCrijqiUTkXuBegFatWlV4UBNcrLFrTEFuN4uHA9NV9W8icjHwtoh0UdWc/Bup6lRgKkB8fLy6kNMEMGvsGlMyJwvBTqBlvuUW3nX53Q0MBFDVH0UkHIgC9jmYy1Rh1tg1puycLARLgfYiEoOnANwM/LbQNtuB/sB0EbkACAf2O5jJVDHW2DWm/BwrBKqaJSKjgfl4vho6TVXXiMjjQJKqJgIPAa+KyP/D0zgeoao29GOKlZGZzYodR/I+8Vtj15jyk0B7342Pj9ekpCS3Yxg/yW3sLk09zNLUQySnHSnQ2E3wvulbY9eYkonIMlWNL+o+t5vFxhRQUmM3tnk97vqVZ5gnvrU1do2pKFYIjGt8aexeE9uUhOhIurWyxq4xTrFCYPwmJ0dZs+uoNXaNqWSsEBi/+dP7K5n7i+cbxNbYNabysEJg/GL+mj3M/WUnd/WO4d5L21hj15hKxAqBcVz6yUzGf7SaC5rW5c/XdCTMhnyMqVSsEBjHTfo0hUMnzvDGiAQrAsZUQva/0jhq0Yb9vL8sjZGXtqFL83puxzHGFMEKgXHM8dNZPDJ3FW0b1eIP/du7HccYUwwbGjKOefbzdexKP8Wc319s5wAYU4n5fEQgIjWdDGKqliVbD/HWj9sYcUk0PVpHuh3HGFOCUguBiFwiIinAOu/yhSLyiuPJTMDKyMxm7AfJtIyM4OGrOrgdxxhTCl+OCP4OXAUcBFDVlcClToYyge3vX25g64ETPD0kjprVbfTRmMrOp6EhVd1RaFW2A1lMFbByxxFe/W4LNye0pHe7KLfjGGN84MvHtR0icgmgIhIG/B+w1tlYJhCdycph7AfJNKpTg0euvcDtOMYYH/lyRPB74H48k9HvBLoC9zmYyQSoVxZuYt2eY0y+MZa64XaJaGMChS9HBB1U9Zb8K0SkN7DYmUgmEK3bc5SXvtnE4K7N6H9BE7fjGGPKwJcjgn/6uM4EqazsHMbMSaZeRBgTru/sdhxjTBkVe0QgIhcDlwCNROTBfHfVxTMHsTEAvP79VpLT0vnn8G5E1qrudhxjTBmVNDRUHajt3aZOvvVHgWFOhjKBY8v+4zz/5QYGdGrCdXFN3Y5jjDkHxRYCVV0ELBKR6aq6zY+ZTIDIyVHGfpBMjWohTLqhi00sY0yA8qVZfFJEpgCdgbzZRFT1csdSmYDwzs/bWJp6mGeHxdG4rk00Y0yg8qVZPAPP5SVigL8CqcBSBzOZAJB2+CTPfLaOPu2j+HWPFm7HMcaUgy+FoKGqvg5kquoiVb0LsKOBIKaq/HnuKhSYfGOsDQkZE+B8GRrK9P65W0SuBXYBdjnJIDZnWRrfbTzA44M70zLSLkprTKDzpRBMEpF6wEN4zh+oC/zRyVCm8tp3NIMnPkmhZ3Qkt17U2u04xpgKUGohUNVPvDfTgX6Qd2axCTKqyviPVnM6K4enh8YSEmJDQsZUBSWdUBYK/AbPNYY+V9XVInId8AgQAXTzT0RTWXy6ajdfpOxl3NUdadOotttxjDEVpKQjgteBlsAS4EUR2QXEA+NU9SM/ZDOVyKETZ5jw8RriWtTjnl/FuB3HGFOBSioE8UCcquaISDiwB2irqgf9E81UJn/97xqOZmQyY9hFVAv1eYZTY0wAKOl/9BlVzQFQ1QxgS1mLgIgMFJH1IrJJRMYVs81vRCRFRNaIyLtleX7jH1+v3cvHK3ZxX992dDyvrttxjDEVrKQjgo4ikuy9LUBb77IAqqpxJT2xt8fwMnAlkAYsFZFEVU3Jt0174M9Ab1U9LCKNy7EvxgFHMzJ59MPVdGhSh/v7tXM7jjHGASUVgvJOMdUT2KSqWwBEZBYwGEjJt83vgJdV9TCAqu4r52uaCvbUvLXsO5bBf27rQfVqNiRkTFVU0kXnynuhueZA/rmO04CLCm1zPoCILMZzaeuJqvp54ScSkXuBewFatWpVzljGV4s3HWDmkh2MvLQNF7as73YcY4xD3P6IVw1oD/QFhgOvikj9whup6lRVjVfV+EaNGvk3YZA6eSaLcXOTiYmqxf+78ny34xhjHORkIdiJ5+unuVp41+WXBiSqaqaqbgU24CkMxmVT5q9nx6FTPD0klvAwm4fImKrMp0IgIhEi0qGMz70UaC8iMSJSHbgZSCy0zUd4jgYQkSg8Q0Vbyvg6poIt23aI6T+kcluv1lzUpqHbcYwxDiu1EIjI9cAK4HPvclcRKfyGfhZVzQJGA/OBtcB7qrpGRB4XkUHezeYDB0UkBVgAPGznKbgrIzObMXOSaVYvgrFXd3Q7jjHGD3y56NxEPN8AWgigqitExKdTS1V1HjCv0LrH8t1W4EHvj6kEXvx6I5v3n+Ctu3pSu4Yv/zyMMYHOl6GhTFVNL7ROnQhj3LV6Zzr/+XYLw3q04NLzrSlvTLDw5SPfGhH5LRDqPQHsD8APzsYy/paZncOYOclE1qrOX67t5HYcY4wf+XJE8ACe+YpPA+/iuRz1Hx3MZFzwn0WbSdl9lCcGd6FezTC34xhj/MiXI4KOqvoo8KjTYYw7Nu49xotfb+LauKYM7HKe23GMMX7myxHB30RkrYg8ISJdHE9k/Co7R3l4TjK1aoTy10Gd3Y5jjHFBqYVAVfvhmZlsP/AfEVklIuMdT2b84o3FW1mx4wgTru9MVO0abscxxrjApxPKVHWPqr4I/B7POQWPlfwIEwi2HTzBc1+s5/KOjRnctZnbcYwxLvHlhLILRGSiiKzCM3n9D3guF2ECWE6OMu6DVYSFhPDkjV0QsfmHjQlWvjSLpwGzgatUdZfDeYyfzFy6nR+3HOSpIbE0rRfhdhxjjItKLQSqerE/ghj/2XXkFE/NW8clbRtyc0LL0h9gjKnSii0EIvKeqv7GOySU/0xin2YoM5WTqvLoh6vIzlGeHhJnQ0LGmBKPCP7P++d1/ghi/OOjFTtZsH4/f7muE60a1nQ7jjGmEii2Wayqu70371PVbfl/gPv8E89UpP3HTvPX/6bQvVV9RlwS7XYcY0wl4cvXR68sYt3VFR3EOG9C4mpOns7m2WFxhIbYkJAxxqOkHsEoPJ/824hIcr676gCLnQ5mKtbnq3czb9UeHr6qA+0a13E7jjGmEimpR/Au8BnwFDAu3/pjqnrI0VSmQh05eYbxH62hU9O63HtpG7fjGGMqmZIKgapqqojcX/gOEYm0YhA4nvhkLUdOnuHNuxIIC3VymmpjTCAq7YjgOmAZnq+P5h9UVsA+WgaABev38cHyNEb3a0fnZvXcjmOMqYSKLQSqep33T5+mpTSVz7GMTB6du4p2jWvzQP92bscxxlRSvlxrqLeI1PLevlVEnheRVs5HM+X1zOfr2H00g2eGxlGjWqjbcYwxlZQvA8b/Ak6KyIXAQ8Bm4G1HU5ly+2nLQd75aTt3XhJDj9YN3I5jjKnEfCkEWaqqwGDgJVV9Gc9XSE0ldepMNmM/SKZVZE3+dNX5bscxxlRyvlx99JiI/Bm4DegjIiGATWpbiT3/5Xq2HTzJu7+7iJrVffkVG2OCmS9HBDfhmbj+LlXdg2cugimOpjLnbMWOI7z+/VaG92zFJW2j3I5jjAkAvkxVuQeYAdQTkeuADFV9y/FkpsxOZ2UzZs5KGtcJ58/XdHQ7jjEmQPjyraHfAEuAXwO/AX4WkWFOBzNl9/KCzWzYe5zJQ7pQN9xG74wxvvFlAPlRIEFV9wGISCPgK2COk8FM2aTsOsorCzZxY7fmXN6xidtxjDEBxJceQUhuEfA66OPjjJ9kZecw9oNk6tcM47HrOrkdxxgTYHw5IvhcROYDM73LNwHznItkyurV77ayamc6L/+2Ow1qVXc7jjEmwPgyZ/HDIjIE+JV31VRV/dDZWMZXm/cf5+9fbWBg5/O4JvY8t+MYYwJQSfMRtAeeA9oCq4A/qepOfwUzpcvJUcbOSSYiLJTHb+hs8w8bY85JSWP904BPgKF4rkD6z7I+uYgMFJH1IrJJRMaVsN1QEVERiS/rawSzt35MJWnbYf5yXSca1wl3O44xJkCVNDRUR1Vf9d5eLyLLy/LEIhIKvIxnqss0YKmIJKpqSqHt6gD/B/xclucPdjsOneTZ+eu57PxGDO3e3O04xpgAVlIhCBeRbvxvHoKI/MuqWlph6AlsUtUtACIyC8/1ilIKbfcE8AzwcBmzBy1V5c9zVyHA5CGxNiRkjCmXkgrBbuD5fMt78i0rcHkpz90c2JFvOQ24KP8GItIdaKmqn4pIsYVARO4F7gVo1cqugP1+UhrfbzrAEzd0oXn9CLfjGGMCXEkT0/Rz8oW9F697HhhR2raqOhWYChAfH69O5qrs9h7N4IlPU+gZE8ktPa0oGmPKz8kTw3YCLfMtt/Cuy1UH6AIsFJFUoBeQaA3j4qkqj364mjNZOTwzNI6QEBsSMsaUn5OFYCnQXkRiRKQ6cDOQmHunqqarapSqRqtqNPATMEhVkxzMFND+m7ybr9bu5aEB5xMTVcvtOMaYKsKxQqCqWcBoYD6wFnhPVdeIyOMiMsip162qDh4/zcTENVzYsj53/6qN23GMMVVIqWcWi+crKbcAbVT1ce98xeep6pLSHquq8yh0OQpVfayYbfv6lDhITfxvCscyMpkyLI5QGxIyxlQgX44IXgEuBoZ7l4/hOT/A+MmXKXv578pdjO7XnvOb2CyhxpiK5ctF5y5S1e4i8guAqh72jvkbP0g/lcmjH66i43l1GNW3rdtxjDFVkC+FINN7lrBC3nwEOY6mMnkmf7qWA8dP89od8VSvZlf/NsZUPF/eWV4EPgQai8iTwPfAZEdTGQC+27if2Uk7uPfStsS1qO92HGNMFeXLZahniMgyoD+ey0vcoKprHU8W5E6czmLcB6toE1WLP17R3u04xpgqzJdvDbUCTgL/zb9OVbc7GSzYTZm/nl3pp3hv5MWEh4W6HccYU4X50iP4FE9/QIBwIAZYD3R2MFdQS0o9xJs/pnJ7r9YkREe6HccYU8X5MjQUm3/Ze6G4+xxLFOQyMrMZMyeZZvUiGDOwo9txjDFBoMxfQ/FefvqiUjc05+QfX21ky4ETPD00llo1fDlgM8aY8vGlR/BgvsUQoDuwy7FEQWxVWjqvfreF38S3oE/7Rm7HMcYECV8+cuY/lTULT8/gA2fiBK8zWTk8PGclDWtV59FrO7kdxxgTREosBN4Tyeqo6p/8lCdo/XvRZtbtOcbU23pQLyLM7TjGmCBSbI9ARKqpajbQ2495gtL6Pcf45zcbuf7CZgzofJ7bcYwxQaakI4IlePoBK0QkEXgfOJF7p6rOdThbUMjOUcZ8kEyd8DAmXm9DQsYY//OlRxAOHMQzR3Hu+QQKWCGoANO+38rKHUd44eauNKxdw+04xpggVFIhaOz9xtBq/lcAcgX1vMEVJfXACZ77Yj1XXNCYQRc2czuOMSZIlVQIQoHaFCwAuawQlFNOjjL2g2SqVwth0g2xeOb/McYY/yupEOxW1cf9liTIzFiynZ+3HuKZobGcVy/c7TjGmCBW0pnF9hHVITuPnOLpeWv5VbsofhPf0u04xpggV1Ih6O+3FEFEVXlk7ipyFJ4aYkNCxhj3FVsIVPWQP4MEi7nLd7Jow37GDOxAy8iabscxxpiyX3TOnLt9xzJ4/JMU4ls34I6Lo92OY4wxgBUCv3rsozWcyszmmWFxhITYkJAxpnKwQuAn81bt5vM1e/jjFe1p26i223GMMSaPFQI/OHziDI99vJouzetyb582bscxxpgCbOYTP3jikxSOnMzkrbsuolqo1V5jTOVi70oOW7BuH3N/2cl9fdvSqVldt+MYY8xZrBA46FhGJo98uIr2jWtz/+Xt3I5jjDFFskLgoKc+W8feoxk8OyyOGtVC3Y5jjDFFskLgkB82H+Ddn7dzV+8YurVq4HYcY4wplqOFQEQGish6EdkkIuOKuP9BEUkRkWQR+VpEWjuZx19Onsli3AeraN2wJg8N6OB2HGOMKZFjhcA73/HLwNVAJ2C4iBSegusXIF5V44A5wLNO5fGnv32xge2HTvLM0DgiqtuQkDGmcnPyiKAnsElVt6jqGWAWMDj/Bqq6QFVPehd/Alo4mMcvlm8/zLTFW7nlolb0atPQ7TjGGFMqJwtBc2BHvuU077ri3A18VtQdInKviCSJSNL+/fsrMGLFOp2VzZg5yTStG864qzu6HccYY3xSKZrFInIrEA9MKep+VZ2qqvGqGt+oUSP/hiuDl77ZxKZ9x3lySCx1wsPcjmOMMT5x8szinUD+WVdaeNcVICJXAI8Cl6nqaQfzOGrNrnReWbiZId2b069DY7fjGGOMz5w8IlgKtBeRGBGpDtwMJObfQES6Af8BBqnqPgezOCozO4cxc5JpULM6j11XuB9ujDGVm2OFQFWzgNHAfGAt8J6qrhGRx0VkkHezKUBt4H0RWSEiicU8XaU29dstrNl1lCcGd6Z+zepuxzHGmDJx9KJzqjoPmFdo3WP5bl/h5Ov7w6Z9x3jh641c3eU8ro5t6nYcY4wps0rRLA5U2TnKmDnJ1Kweyl8Hd3Y7jjHGnBMrBOXw5g+pLN9+hMeu60TjOuFuxzHGmHNiheAcbT94kinz19O3QyNu7FbS6RHGGFO5WSE4B6rKuLnJhIYIk2+MRcTmHzbGBC4rBOdg1tId/LD5IH++piPN6ke4HccYY8rFCkEZ7U4/xeRP19KrTSTDE1q5HccYY8rNCkEZqCrjP1xNZk4OzwyNIyTEhoSMMYHPCkEZJK7cxdfr9vGnAR1o3bCW23GMMaZCWCHw0YHjp5mYuIauLetzZ+8Yt+MYY0yFsULgowmJazhxOpspw+IItSEhY0wVYoXAB/PX7OHT5N08cHk72jep43YcY4ypUFYISpF+MpPxH63mgqZ1+X3ftm7HMcaYCufoReeqgkmfpnDoxBneGJFAWKjVTWNM1WPvbCVYtGE/7y9LY+SlbejSvJ7bcYwxxhFWCIpx/HQWj8xdRdtGtfhD//ZuxzHGGMfY0FAxnv18HbvSTzHn9xcTHhbqdhxjjHGMHREUYcnWQ7z14zbuuDiaHq0j3Y5jjDGOskJQSEZmNmM/SKZlZARjBnZwO44xxjjOhoYK+fuXG9h64AQz7rmImtXtr8cYU/XZEUE+K3cc4dXvtnBzQkt6t4tyO44xxviFFQKvM1k5jP0gmUZ1avDItRe4HccYY/zGxj68Xlm4iXV7jvHa7fHUDQ9zO47xQWZmJmlpaWRkZLgdxZhKIzw8nBYtWhAW5vv7mBUCYN2eo7z0zSYGd23GFZ2auB3H+CgtLY06deoQHR1t04Uag2fOlIMHD5KWlkZMjO9XSQ76oaGs7BzGzEmmXkQYE67v7HYcUwYZGRk0bNjQioAxXiJCw4YNy3yUHPRHBK9/v5XktHT+ObwbkbWqux3HlJEVAWMKOpf/E0F9RLBl/3Ge/3IDV3ZqwnVxTd2OY4wxrgjaQpCTo4z7YBU1qoUw6YYu9snSBKzU1FS6dOni2PNPnz6dXbt25S3fc889pKSklPt5U1NTeffdd8v9PKdOneKyyy4jOzs7b90//vEPwsPDSU9Pz1s3ffp0Ro8eXeCxffv2JSkpCYDjx48zcuRI2rZtS48ePejbty8///xzubKpKn/4wx9o164dcXFxLF++/Kxtjh07RteuXfN+oqKi+OMf/wjA888/T6dOnYiLi6N///5s27YNgP379zNw4MByZcsvaAvBOz9vY0nqIcZf14kmdcPdjmNMpVW4ELz22mt06tSp3M97LoUgKyvrrHXTpk1jyJAhhIb+75pgM2fOJCEhgblz5/r83Pfccw+RkZFs3LiRZcuW8cYbb3DgwIEy5Svss88+Y+PGjWzcuJGpU6cyatSos7apU6cOK1asyPtp3bo1Q4YMAaBbt24kJSWRnJzMsGHDGDNmDACNGjWiadOmLF68uFz5cgVljyDt8Eme+WwdfdpH8eseLdyOYyrAX/+7hpRdRyv0OTs1q1vqFwjeeecdXnzxRc6cOcNFF13EK6+8wvLly7n77rtZsmQJ2dnZ9OzZk9mzZxMdHc3gwYM5fPgwmZmZTJo0icGDB5OamsrAgQPp1asXP/zwAwkJCdx5551MmDCBffv2MWPGDHr27MnEiRPZvHkzmzZt4sCBA4wZM4bf/e53BfJkZ2czbtw4Fi5cyOnTp7n//vsZOXKkT7kB7r77bpKSkhAR7rrrLlq2bElSUhK33HILERER/Pjjj1x99dU899xzxMfHU7t2bUaNGsW8efNo2rQpkydPZsyYMWzfvp1//OMfDBo0iNTUVG677TZOnDgBwEsvvcQll1zCuHHjWLt2LV27duWOO+5g1KhRjBo1iqSkJKpVq8bzzz9Pv379mD59OnPnzuX48eNkZ2ezaNGiAvsyY8aMAgVl8+bNHD9+nFdeeYUnn3ySO++8s9Tf9ebNm/n555+ZMWMGISGez8cxMTFl+uZNUT7++GNuv/12RIRevXpx5MgRdu/eTdOmRQ9Fb9iwgX379tGnTx8A+vXrl3dfr169eOedd/KWb7jhBmbMmEHv3r3LlRGCsBCoKn+euwoFJt8Ya0NC5pytXbuW2bNns3jxYsLCwrjvvvuYMWMGt99+O4MGDWL8+PGcOnWKW2+9lS5dupCVlcWHH35I3bp1OXDgAL169WLQoEEAbNq0iffff59p06aRkJDAu+++y/fff09iYiKTJ0/mo48+AiA5OZmffvqJEydO0K1bN6699toCmV5//XXq1avH0qVLOX36NL1792bAgAEF3tCKy925c2d27tzJ6tWrAThy5Aj169fnpZdeynvjL+zEiRNcfvnlTJkyhRtvvJHx48fz5ZdfkpKSwh133MGgQYNo3LgxX375JeHh4WzcuJHhw4eTlJTE008/zXPPPccnn3wCwN/+9jdEhFWrVrFu3ToGDBjAhg0bAFi+fDnJyclERha8COSZM2fYsmUL0dHReetmzZrFzTffTJ8+fVi/fj179+6lSZOSvxa+Zs0aunbtWuCoojg33XQT69evP2v9gw8+yO23315g3c6dO2nZsmXecosWLdi5c2exhWDWrFncdNNNRb4vvf7661x99dV5y/Hx8YwfP77UvL4IukIwZ1ka3208wF8HdaZlZE2345gK4sZXf7/++muWLVtGQkIC4Bmrbty4MQCPPfYYCQkJhIeH8+KLLwKeDyGPPPII3377LSEhIezcuZO9e/cCnk+fsbGxAHTu3Jn+/fsjIsTGxpKampr3moMHDyYiIoKIiAj69evHkiVL6Nq1a979X3zxBcnJycyZMweA9PR0Nm7cWKAQFJf7+uuvZ8uWLTzwwANce+21DBgwoNS/g+rVq+eNVcfGxlKjRg3CwsIK5M7MzGT06NGsWLGC0NDQvDf3wr7//nseeOABADp27Ejr1q3ztr3yyivPKgIABw4coH79+gXWzZw5kw8//JCQkBCGDh3K+++/z+jRo4v90FfWD4OzZ88u0/ZlMWvWLN5+++2z1r/zzjskJSUVOBpq3LhxgSG78nC0EIjIQOAFIBR4TVWfLnR/DeAtoAdwELhJVVOdyrPvaAZPfJJCQnQDbuvV2qmXMUFCVbnjjjt46qmnzrrv4MGDHD9+nMzMTDIyMqhVqxYzZsxg//79LFu2jLCwMKKjo/O+712jRo28x4aEhOQth4SEFBgXL/ymVXhZVfnnP//JVVdddU65V65cyfz58/n3v//Ne++9x7Rp00r8OwgLC8vLUFzuv//97zRp0oSVK1eSk5NDeHjZe3K1atUqcn1ERESB78yvWrWKjRs3cuWVVwKeI4aYmBhGjx5Nw4YNOXz4cIHHHzp0iKioKOrXr8/KlSvJzs4u9aigLEcEzZs3Z8eOHXnLaWlpNG/evMjnXblyJVlZWfTo0aPA+q+++oonn3ySRYsWFfh3kpGRQURERIlZfeVYs1hEQoGXgauBTsBwESncYbobOKyq7YC/A884lUdVGf/Rak5n5fDM0DhCQmxIyJRP//79mTNnDvv27QM8byq53+oYOXIkTzzxBLfccgtjx44FPJ/OGzduTFhYGAsWLMjbtiw+/vhjMjIyOHjwIAsXLsz7VJ/rqquu4l//+heZmZmAZ8w5d2y+tNwHDhwgJyeHoUOHMmnSpLxvuNSpU4djx46VOWuu9PR0mjZtSkhICG+//Xbet3sKP2+fPn2YMWNGXu7t27fToUPJl4Jv0KAB2dnZecVg5syZTJw4kdTUVFJTU9m1axe7du1i27ZtJCQksHjxYvbs2QNAUlISp0+fpmXLlrRt25b4+HgmTJiAqgKeZvann3561mvOnj27QHM396dwEQAYNGgQb731FqrKTz/9RL169YodFpo5cybDhw8vsO6XX35h5MiRJCYm5h1t5tqwYUOFfVvMySOCnsAmVd0CICKzgMFA/u+dDQYmem/PAV4SEdHc30QF+nTVbr5I2cu4qzvSplHtin56E4Q6derEpEmTGDBgADk5OYSFhfHyyy+zaNEiwsLC+O1vf0t2djaXXHIJ33zzDbfccgvXX389sbGxxMfH07FjxzK/ZlxcHP369ePAgQP85S9/oVmzZgWGju655x5SU1Pp3r07qkqjRo3y+gul5Y6IiODOO+8kJycHIO+IYcSIEfz+97/PaxaX1X333cfQoUN56623GDhwYN6n+7i4OEJDQ7nwwgsZMWIE9913H6NGjSI2NpZq1aoxffr0Ap+AizNgwAC+//57rrjiCmbNmsW8efMK3H/jjTcya9Ysxo4dywsvvMA111xDTk4OtWvXZubMmXnN4ddee42HHnqIdu3aERERQVRUFFOmTCnz/uZ3zTXXMG/ePNq1a0fNmjV544038u7r2rUrK1asyFt+7733zsr+8MMPc/z4cX79618D0KpVKxITEwFYsGDBWT2ic6aqjvwAw/AMB+Uu3wa8VGib1UCLfMubgaginuteIAlIatWqlZ6Lhev36T1vLtXMrOxzerypfFJSUtyO4FcTJkzQKVOmuB2j0lm2bJneeuutbsfwuz59+uihQ4eKvK+o/xtAkhbzfh0QzWJVnQpMBYiPjz+no4XLzm/EZec3qtBcxhj3de/enX79+vk0vl9V7N+/nwcffJAGDRpUyPM5WQh2Ai3zLbfwritqmzQRqQbUw9M0NsYUMnHiRLcjVFp33XWX2xH8qlGjRtxwww0V9nxOnlm8FGgvIjEiUh24GUgstE0icIf39jDgG+8hjDE+sX8uxhR0Lv8nHCsEqpoFjAbmA2uB91R1jYg8LiKDvJu9DjQUkU3Ag8A4p/KYqic8PJyDBw9aMTDGS73zEZT1K7oSaP+J4uPjNfciUSa42QxlxpytuBnKRGSZqp59ejhBeGaxqTrCwsLKfS0YY0wQX33UGGOMhxUCY4wJclYIjDEmyAVcs1hE9gNlv0iLRxRQvpkmAo/tc3CwfQ4O5dnn1qpa5Fm1AVcIykNEkorrmldVts/BwfY5ODi1zzY0ZIwxQc4KgTHGBLlgKwRT3Q7gAtvn4GD7HBwc2eeg6hEYY4w5W7AdERhjjCnECoExxgS5KlkIRGSgiKwXkU0ictYVTUWkhojM9t7/s4hEuxCzQvmwzw+KSIqIJIvI1yLS2o2cFam0fc633VARUREJ+K8a+rLPIvIb7+96jYi86++MFc2Hf9utRGSBiPzi/fd9jRs5K4qITBORfSKyupj7RURe9P59JItI93K/aHFTlwXqDxCKZ8rLNkB1YCXQqdA29wH/9t6+GZjtdm4/7HM/oKb39qhg2GfvdnWAb4GfgHi3c/vh99we+AVo4F1u7HZuP+zzVGCU93YnINXt3OXc50uB7sDqYu6/BvgMEKAX8HN5X7MqHhH0BDap6hZVPQPMAgYX2mYw8Kb39hygv4iIHzNWtFL3WVUXqOpJ7+JPeGaMC2S+/J4BngCeAarCtap92effAS+r6mEAVd3n54wVzZd9VqCu93Y9YJcf81U4Vf0WOFTCJoOBt9TjJ6C+iDQtz2tWxULQHNiRbznNu67IbdQzgU460NAv6Zzhyz7ndzeeTxSBrNR99h4yt1TVT/0ZzEG+/J7PB84XkcUi8pOIDPRbOmf4ss8TgVtFJA2YBzzgn2iuKev/91LZfARBRkRuBeKBy9zO4iQRCQGeB0a4HMXfquEZHuqL56jvWxGJVdUjboZy2HBguqr+TUQuBt4WkS6qmuN2sEBRFY8IdgIt8y238K4rchsRqYbncPKgX9I5w5d9RkSuAB4FBqnqaT9lc0pp+1wH6AIsFJFUPGOpiQHeMPbl95wGJKpqpqpuBTbgKQyBypd9vht4D0BVfwTC8Vycrary6f97WVTFQrAUaC8iMSJSHU8zOLHQNonAHd7bw4Bv1NuFCVCl7rOIdAP+g6cIBPq4MZSyz6qarqpRqhqtqtF4+iKDVDWQ5zn15d/2R3iOBhCRKDxDRVv8mLGi+bLP24H+ACJyAZ5CsN+vKf0rEbjd++2hXkC6qu4uzxNWuaEhVc0SkdHAfDzfOJimqmtE5HEgSVUTgdfxHD5uwtOUudm9xOXn4z5PAWoD73v74ttVdZBrocvJx32uUnzc5/nAABFJAbKBh1U1YI92fdznh4BXReT/4WkcjwjkD3YiMhNPMY/y9j0mAGEAqvpvPH2Qa4BNwEngznK/ZgD/fRljjKkAVXFoyBhjTBlYITDGmCBnhcAYY4KcFQJjjAlyVgiMMSbIWSEwlZKIZIvIinw/0SVse7wCXm+6iGz1vtZy7xmqZX2O10Skk/f2I4Xu+6G8Gb3Pk/v3slpE/isi9UvZvmugX43TOM++PmoqJRE5rqq1K3rbEp5jOvCJqs4RkQHAc6oaV47nK3em0p5XRN4ENqjqkyVsPwLPVVdHV3QWU3XYEYEJCCJS2zuPwnIRWSUiZ11pVESaisi3+T4x9/GuHyAiP3of+76IlPYG/S3QzvvYB73PtVpE/uhdV0tEPhWRld71N3nXLxSReBF5Gojw5pjhve+4989ZInJtvszTRWSYiISKyBQRWeq9xvxIH/5afsR7sTER6endx19E5AcR6eA9E/dx4CZvlpu82aeJyBLvtkVdsdUEG7evvW0/9lPUD56zYld4fz7EcxZ8Xe99UXjOqsw9oj3u/fMh4FHv7VA81xuKwvPGXsu7fizwWBGvNx0Y5r39a+BnoAewCqiF56zsNUA3YCjwar7H1vP+uRDvnAe5mfJtk5vxRuBN7+3qeK4iGQHcC4z3rq8BJAExReQ8nm//3gcGepfrAtW8t68APvDeHgG8lO/xk4Fbvbfr47kWUS23f9/24+5PlbvEhKkyTqlq19wFEQkDJovIpUAOnk/CTYA9+R6zFJjm3fYjVV0hIpfhmaxksffSGtXxfJIuyhQRGY/nOjV347l+zYeqesKbYS7QB/gc+JuIPINnOOm7MuzXZ8ALIlIDGAh8q6qnvMNRcSIyzLtdPTwXi9ta6PERIrLCu/9rgS/zbf+miLTHc5mFsGJefwAwSET+5F0OB1p5n8sEKSsEJlDcAjQCeqhqpniuKBqefwNV/dZbKK4FpovI88Bh4EtVHe7DazysqnNyF0Skf1EbqeoG8cx1cA0wSUS+VtXHfdkJVc0QkYXAVcBNeCZaAc9sUw+o6vxSnuKUqnYVkZp4rr9zP/Aingl4Fqjqjd7G+sJiHi/AUFVd70teExysR2ACRT1gn7cI9APOmnNZPPMw71XVV4HX8Ez39xPQW0Ryx/xricj5Pr7md8ANIlJTRGrhGdb5TkSaASdV9R08F/Mras7YTO+RSVFm47lQWO7RBXje1EflPkZEzve+ZpHUM9vcH4CH5H+XUs+9FPGIfJsewzNElms+8IB4D4/Ec1VaE+SsEJhAMQOIF5FVwO3AuiK26QusFJFf8HzafkFV9+N5Y5wpIsl4hoU6+vKCqrocT+9gCZ6ewWuq+gsQCyzxDtFMACYV8fCpQHJus7iQL/BMDPSVeqZfBE/hSgGWi2fS8v9QyhG7N0synolZngWe8u57/sctADrlNovxHDmEebOt8S6bIGdfHzXGmCBnRwTGGBPkrBAYY0yQs0JgjDFBzgqBMcYEOSsExhgT5KwQGGNMkLNCYIwxQe7/A3CX2nt5i/GOAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "fpr, tpr, thresholds = roc_curve(y_predicted, y_test_smoted)\n",
    "roc_auc = auc(fpr, tpr)\n",
    "display = RocCurveDisplay(\n",
    "    fpr=fpr, tpr=tpr, roc_auc=roc_auc, estimator_name='example estimator')\n",
    "display.plot()\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# F1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "6 fits failed out of a total of 9.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "3 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 660, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 227, in fit\n",
      "    self.stack_method_ = [\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 228, in <listcomp>\n",
      "    self._method_name(name, est, meth)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 157, in _method_name\n",
      "    raise ValueError(\n",
      "ValueError: Underlying estimator svc does not implement the method predict_proba.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "3 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 660, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 227, in fit\n",
      "    self.stack_method_ = [\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 228, in <listcomp>\n",
      "    self._method_name(name, est, meth)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 157, in _method_name\n",
      "    raise ValueError(\n",
      "ValueError: Underlying estimator knn_f1 does not implement the method decision_function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [     nan      nan 0.596337]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.58304388        nan 0.49642857        nan        nan 0.62142574\n",
      " 0.49642857        nan 0.59837104 0.60572398        nan 0.60069094]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.61111111        nan 0.54166667        nan        nan 0.61111111\n",
      " 0.54166667        nan 0.61111111 0.61111111        nan 0.63611111]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.62628205        nan 0.45631579        nan        nan 0.63743316\n",
      " 0.45631579        nan 0.59807692 0.61439394        nan 0.63141026]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.49809524        nan 0.4370696         nan        nan 0.53730769\n",
      " 0.35438561        nan 0.53142857 0.56              nan 0.49809524]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.50393162        nan 0.42470667        nan        nan 0.49752137\n",
      " 0.41591546        nan 0.48994561 0.48994561        nan 0.46837607]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.57260073        nan 0.3804995         nan        nan 0.64505495\n",
      " 0.3804995         nan 0.67619048 0.65714286        nan 0.59166667]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.62211999        nan 0.52431078        nan        nan 0.6679164\n",
      " 0.52431078        nan 0.66425339 0.6745098         nan 0.61333333]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.68571429        nan 0.51428571        nan        nan 0.68571429\n",
      " 0.51428571        nan 0.62857143 0.65714286        nan 0.68571429]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.49047619        nan 0.46190476        nan        nan 0.55238095\n",
      " 0.37619048        nan 0.51904762 0.55238095        nan 0.49047619]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.50952381        nan 0.47142857        nan        nan 0.50952381\n",
      " 0.47142857        nan 0.48095238 0.48095238        nan 0.47619048]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.58571429        nan 0.36666667        nan        nan 0.64285714\n",
      " 0.36666667        nan 0.7        0.67142857        nan 0.60952381]\n",
      "  warnings.warn(\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:378: FitFailedWarning: \n",
      "25 fits failed out of a total of 60.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'nan_euclidean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['kd_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "5 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 215, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 493, in _fit\n",
      "    self._check_algorithm_metric()\n",
      "  File \"c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 434, in _check_algorithm_metric\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'cosine' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['ball_tree']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "c:\\Users\\Mike\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\sklearn\\model_selection\\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.63809524        nan 0.58095238        nan        nan 0.7\n",
      " 0.58095238        nan 0.66666667 0.66666667        nan 0.6       ]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'stack_method': 'predict'}"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "stacking_classifie_optimall_params = GridSearchCV(StackingClassifier([('knn_f1', knn_optimal_n_neighbors_by_f1), \n",
    "                                                                      ('knn_recall', knn_optimal_n_neighbors_by_recall), \n",
    "                                                                      ('svc', svc_optimal)]),\n",
    "                                                  {'stack_method': ['predict_proba', 'decision_function', 'predict']},\n",
    "                                                  n_jobs=4,\n",
    "                                                  scoring='f1',\n",
    "                                                  cv=3\n",
    "                                                  ).fit(X_train_smoted, y_train_smoted)\n",
    "stacking_classifie_optimall_params.best_params_\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "y_predicted = stacking_classifie_optimall_params.predict(X_test_smoted)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[30 11]\n",
      " [14 33]]\n"
     ]
    }
   ],
   "source": [
    "print(confusion_matrix(y_test_smoted, y_predicted))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "              precision    recall  f1-score   support\n",
      "\n",
      "       False       0.68      0.73      0.71        41\n",
      "        True       0.75      0.70      0.73        47\n",
      "\n",
      "    accuracy                           0.72        88\n",
      "   macro avg       0.72      0.72      0.72        88\n",
      "weighted avg       0.72      0.72      0.72        88\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print(classification_report(y_test_smoted, y_predicted))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<sklearn.metrics._plot.roc_curve.RocCurveDisplay at 0x1e095e8f2b0>"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYIAAAEGCAYAAABo25JHAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAAu0UlEQVR4nO3deXxU9fX/8ddJCCTshACyJyyCQCJLgihFQRRxAwVapW64VIpiv/1pBapUqCIuWFut2hYVcUFAETVVFDdAxQUCQoCwQ4Cwr2ENZDm/P2aSJiHLhOTOzWTO8/HIg7l37sy8L4E5cz9n7v2IqmKMMSZ4hbgdwBhjjLusEBhjTJCzQmCMMUHOCoExxgQ5KwTGGBPkqrkdoKyioqI0Ojra7RjGGBNQli1bdkBVGxV1X8AVgujoaJKSktyOYYwxAUVEthV3nw0NGWNMkLNCYIwxQc4KgTHGBDkrBMYYE+SsEBhjTJBzrBCIyDQR2Sciq4u5X0TkRRHZJCLJItLdqSzGGGOK5+QRwXRgYAn3Xw209/7cC/zLwSzGGGOK4VghUNVvgUMlbDIYeEs9fgLqi0hTp/IYY0wgOnUmmx82HeAfX21gza50R17DzRPKmgM78i2nedftLryhiNyL56iBVq1a+SWcMca44cjJMyxNPczS1EMs2XqI1TvTycpRRKBh7Rp0blavwl8zIM4sVtWpwFSA+Ph4m0nHGFNl7DpyKu9Nf2nqITbsPQ5A9dAQ4lrU43eXtqFndCTdWzegXkSYIxncLAQ7gZb5llt41xljTJWkqmzef5wlW//3iX/nkVMA1K5Rje6tGzDowmYkREdyYcv6hIeF+iWXm4UgERgtIrOAi4B0VT1rWMgYYwJVVnYOa3YdzXvTT9p2mEMnzgAQVbs6CdGR3P2rGHrGRNLxvDpUC3XnG/2OFQIRmQn0BaJEJA2YAIQBqOq/gXnANcAm4CRwp1NZjDHGH06dyeaX7YfzxviXbz/MyTPZALSKrEm/Do3pGdOAhOhIYqJqISIuJ/ZwrBCo6vBS7lfgfqde3xhjnFZSY7dDkzoM69GChOhIesZE0qRuuNtxixUQzWJjjKkMfGnsJkQ3oEfrSMcau06wQmCMMUWorI1dJ1ghMMYYAqex6wQrBMaYoHTqTDa/7DjM0q2B1dh1ghUCY0xQOHLyDEm5jd1UT2M3MzvwGrtOsEJgjKmS8jd2k1IPs37vMQDCQoW4FvW5+1dt6BkTeI1dJ1ghMMYEPF8au9df2JT46Ei6Bnhj1wlWCIwxASeYG7tOsEJgjKn0rLHrLCsExphKxxq7/mWFwBjjut3pp/LO1l261Rq7/maFwBjjV7mN3aWph1m61fOJP+2wp7Fbq3oo3Vs34Lq4piTEWGPXX6wQGGMc5Utj967e1th1kxUCY0yFssZu4LFCYIwpF18buwnRkZxXzxq7lZEVAmNMmfjc2G0VSb2a1tgNBFYIjDHF8jR2T3jf9K2xW1VZITDG5MnKziFl99G8T/xJqYc56G3sNqzlaeze2TuGntGRXNDUGrtVhRUCY4JY/sZu0rZDLN92mBP5Grt9OzQmIboBCTGRtLHGbpVlhcCYIJJ+MtMzzFNMY3eoNXaDkhUCY6owa+waX1ghMKaKsMauOVdWCIwJUNbYNRXFCoExASIjM5tfth/JG+O3xq6pKFYIjKmk0k9mkrTNM8SzdOshVllj1zjECoExlcSe9Iy8N/2lqYdYv/cYqtbYNc6zQmCMCwo0dr0/Ow4VbOxeG2uNXeMfVgiM8QNfGrsjLrHGrnGHFQJjHFBSY7dlZASXdWhEz+hIa+yaSsEKgTEVoLTG7pDuLUiIiaSnNXZNJWSFwJhzYI1dU5U4WghEZCDwAhAKvKaqTxe6vxXwJlDfu804VZ3nZCZjykpV2XLgRN7ZutbYNVWNY4VAREKBl4ErgTRgqYgkqmpKvs3GA++p6r9EpBMwD4h2KpMxvsjKzmHt7mN5n/iTth3iwHFr7Jqqy8kjgp7AJlXdAiAis4DBQP5CoEBd7+16wC4H8xhTpNIau5eeb41dU7U5WQiaAzvyLacBFxXaZiLwhYg8ANQCrijqiUTkXuBegFatWlV4UBNcrLFrTEFuN4uHA9NV9W8icjHwtoh0UdWc/Bup6lRgKkB8fLy6kNMEMGvsGlMyJwvBTqBlvuUW3nX53Q0MBFDVH0UkHIgC9jmYy1Rh1tg1puycLARLgfYiEoOnANwM/LbQNtuB/sB0EbkACAf2O5jJVDHW2DWm/BwrBKqaJSKjgfl4vho6TVXXiMjjQJKqJgIPAa+KyP/D0zgeoao29GOKlZGZzYodR/I+8Vtj15jyk0B7342Pj9ekpCS3Yxg/yW3sLk09zNLUQySnHSnQ2E3wvulbY9eYkonIMlWNL+o+t5vFxhRQUmM3tnk97vqVZ5gnvrU1do2pKFYIjGt8aexeE9uUhOhIurWyxq4xTrFCYPwmJ0dZs+uoNXaNqWSsEBi/+dP7K5n7i+cbxNbYNabysEJg/GL+mj3M/WUnd/WO4d5L21hj15hKxAqBcVz6yUzGf7SaC5rW5c/XdCTMhnyMqVSsEBjHTfo0hUMnzvDGiAQrAsZUQva/0jhq0Yb9vL8sjZGXtqFL83puxzHGFMEKgXHM8dNZPDJ3FW0b1eIP/du7HccYUwwbGjKOefbzdexKP8Wc319s5wAYU4n5fEQgIjWdDGKqliVbD/HWj9sYcUk0PVpHuh3HGFOCUguBiFwiIinAOu/yhSLyiuPJTMDKyMxm7AfJtIyM4OGrOrgdxxhTCl+OCP4OXAUcBFDVlcClToYyge3vX25g64ETPD0kjprVbfTRmMrOp6EhVd1RaFW2A1lMFbByxxFe/W4LNye0pHe7KLfjGGN84MvHtR0icgmgIhIG/B+w1tlYJhCdycph7AfJNKpTg0euvcDtOMYYH/lyRPB74H48k9HvBLoC9zmYyQSoVxZuYt2eY0y+MZa64XaJaGMChS9HBB1U9Zb8K0SkN7DYmUgmEK3bc5SXvtnE4K7N6H9BE7fjGGPKwJcjgn/6uM4EqazsHMbMSaZeRBgTru/sdhxjTBkVe0QgIhcDlwCNROTBfHfVxTMHsTEAvP79VpLT0vnn8G5E1qrudhxjTBmVNDRUHajt3aZOvvVHgWFOhjKBY8v+4zz/5QYGdGrCdXFN3Y5jjDkHxRYCVV0ELBKR6aq6zY+ZTIDIyVHGfpBMjWohTLqhi00sY0yA8qVZfFJEpgCdgbzZRFT1csdSmYDwzs/bWJp6mGeHxdG4rk00Y0yg8qVZPAPP5SVigL8CqcBSBzOZAJB2+CTPfLaOPu2j+HWPFm7HMcaUgy+FoKGqvg5kquoiVb0LsKOBIKaq/HnuKhSYfGOsDQkZE+B8GRrK9P65W0SuBXYBdjnJIDZnWRrfbTzA44M70zLSLkprTKDzpRBMEpF6wEN4zh+oC/zRyVCm8tp3NIMnPkmhZ3Qkt17U2u04xpgKUGohUNVPvDfTgX6Qd2axCTKqyviPVnM6K4enh8YSEmJDQsZUBSWdUBYK/AbPNYY+V9XVInId8AgQAXTzT0RTWXy6ajdfpOxl3NUdadOotttxjDEVpKQjgteBlsAS4EUR2QXEA+NU9SM/ZDOVyKETZ5jw8RriWtTjnl/FuB3HGFOBSioE8UCcquaISDiwB2irqgf9E81UJn/97xqOZmQyY9hFVAv1eYZTY0wAKOl/9BlVzQFQ1QxgS1mLgIgMFJH1IrJJRMYVs81vRCRFRNaIyLtleX7jH1+v3cvHK3ZxX992dDyvrttxjDEVrKQjgo4ikuy9LUBb77IAqqpxJT2xt8fwMnAlkAYsFZFEVU3Jt0174M9Ab1U9LCKNy7EvxgFHMzJ59MPVdGhSh/v7tXM7jjHGASUVgvJOMdUT2KSqWwBEZBYwGEjJt83vgJdV9TCAqu4r52uaCvbUvLXsO5bBf27rQfVqNiRkTFVU0kXnynuhueZA/rmO04CLCm1zPoCILMZzaeuJqvp54ScSkXuBewFatWpVzljGV4s3HWDmkh2MvLQNF7as73YcY4xD3P6IVw1oD/QFhgOvikj9whup6lRVjVfV+EaNGvk3YZA6eSaLcXOTiYmqxf+78ny34xhjHORkIdiJ5+unuVp41+WXBiSqaqaqbgU24CkMxmVT5q9nx6FTPD0klvAwm4fImKrMp0IgIhEi0qGMz70UaC8iMSJSHbgZSCy0zUd4jgYQkSg8Q0Vbyvg6poIt23aI6T+kcluv1lzUpqHbcYwxDiu1EIjI9cAK4HPvclcRKfyGfhZVzQJGA/OBtcB7qrpGRB4XkUHezeYDB0UkBVgAPGznKbgrIzObMXOSaVYvgrFXd3Q7jjHGD3y56NxEPN8AWgigqitExKdTS1V1HjCv0LrH8t1W4EHvj6kEXvx6I5v3n+Ctu3pSu4Yv/zyMMYHOl6GhTFVNL7ROnQhj3LV6Zzr/+XYLw3q04NLzrSlvTLDw5SPfGhH5LRDqPQHsD8APzsYy/paZncOYOclE1qrOX67t5HYcY4wf+XJE8ACe+YpPA+/iuRz1Hx3MZFzwn0WbSdl9lCcGd6FezTC34xhj/MiXI4KOqvoo8KjTYYw7Nu49xotfb+LauKYM7HKe23GMMX7myxHB30RkrYg8ISJdHE9k/Co7R3l4TjK1aoTy10Gd3Y5jjHFBqYVAVfvhmZlsP/AfEVklIuMdT2b84o3FW1mx4wgTru9MVO0abscxxrjApxPKVHWPqr4I/B7POQWPlfwIEwi2HTzBc1+s5/KOjRnctZnbcYwxLvHlhLILRGSiiKzCM3n9D3guF2ECWE6OMu6DVYSFhPDkjV0QsfmHjQlWvjSLpwGzgatUdZfDeYyfzFy6nR+3HOSpIbE0rRfhdhxjjItKLQSqerE/ghj/2XXkFE/NW8clbRtyc0LL0h9gjKnSii0EIvKeqv7GOySU/0xin2YoM5WTqvLoh6vIzlGeHhJnQ0LGmBKPCP7P++d1/ghi/OOjFTtZsH4/f7muE60a1nQ7jjGmEii2Wayqu70371PVbfl/gPv8E89UpP3HTvPX/6bQvVV9RlwS7XYcY0wl4cvXR68sYt3VFR3EOG9C4mpOns7m2WFxhIbYkJAxxqOkHsEoPJ/824hIcr676gCLnQ5mKtbnq3czb9UeHr6qA+0a13E7jjGmEimpR/Au8BnwFDAu3/pjqnrI0VSmQh05eYbxH62hU9O63HtpG7fjGGMqmZIKgapqqojcX/gOEYm0YhA4nvhkLUdOnuHNuxIIC3VymmpjTCAq7YjgOmAZnq+P5h9UVsA+WgaABev38cHyNEb3a0fnZvXcjmOMqYSKLQSqep33T5+mpTSVz7GMTB6du4p2jWvzQP92bscxxlRSvlxrqLeI1PLevlVEnheRVs5HM+X1zOfr2H00g2eGxlGjWqjbcYwxlZQvA8b/Ak6KyIXAQ8Bm4G1HU5ly+2nLQd75aTt3XhJDj9YN3I5jjKnEfCkEWaqqwGDgJVV9Gc9XSE0ldepMNmM/SKZVZE3+dNX5bscxxlRyvlx99JiI/Bm4DegjIiGATWpbiT3/5Xq2HTzJu7+7iJrVffkVG2OCmS9HBDfhmbj+LlXdg2cugimOpjLnbMWOI7z+/VaG92zFJW2j3I5jjAkAvkxVuQeYAdQTkeuADFV9y/FkpsxOZ2UzZs5KGtcJ58/XdHQ7jjEmQPjyraHfAEuAXwO/AX4WkWFOBzNl9/KCzWzYe5zJQ7pQN9xG74wxvvFlAPlRIEFV9wGISCPgK2COk8FM2aTsOsorCzZxY7fmXN6xidtxjDEBxJceQUhuEfA66OPjjJ9kZecw9oNk6tcM47HrOrkdxxgTYHw5IvhcROYDM73LNwHznItkyurV77ayamc6L/+2Ow1qVXc7jjEmwPgyZ/HDIjIE+JV31VRV/dDZWMZXm/cf5+9fbWBg5/O4JvY8t+MYYwJQSfMRtAeeA9oCq4A/qepOfwUzpcvJUcbOSSYiLJTHb+hs8w8bY85JSWP904BPgKF4rkD6z7I+uYgMFJH1IrJJRMaVsN1QEVERiS/rawSzt35MJWnbYf5yXSca1wl3O44xJkCVNDRUR1Vf9d5eLyLLy/LEIhIKvIxnqss0YKmIJKpqSqHt6gD/B/xclucPdjsOneTZ+eu57PxGDO3e3O04xpgAVlIhCBeRbvxvHoKI/MuqWlph6AlsUtUtACIyC8/1ilIKbfcE8AzwcBmzBy1V5c9zVyHA5CGxNiRkjCmXkgrBbuD5fMt78i0rcHkpz90c2JFvOQ24KP8GItIdaKmqn4pIsYVARO4F7gVo1cqugP1+UhrfbzrAEzd0oXn9CLfjGGMCXEkT0/Rz8oW9F697HhhR2raqOhWYChAfH69O5qrs9h7N4IlPU+gZE8ktPa0oGmPKz8kTw3YCLfMtt/Cuy1UH6AIsFJFUoBeQaA3j4qkqj364mjNZOTwzNI6QEBsSMsaUn5OFYCnQXkRiRKQ6cDOQmHunqqarapSqRqtqNPATMEhVkxzMFND+m7ybr9bu5aEB5xMTVcvtOMaYKsKxQqCqWcBoYD6wFnhPVdeIyOMiMsip162qDh4/zcTENVzYsj53/6qN23GMMVVIqWcWi+crKbcAbVT1ce98xeep6pLSHquq8yh0OQpVfayYbfv6lDhITfxvCscyMpkyLI5QGxIyxlQgX44IXgEuBoZ7l4/hOT/A+MmXKXv578pdjO7XnvOb2CyhxpiK5ctF5y5S1e4i8guAqh72jvkbP0g/lcmjH66i43l1GNW3rdtxjDFVkC+FINN7lrBC3nwEOY6mMnkmf7qWA8dP89od8VSvZlf/NsZUPF/eWV4EPgQai8iTwPfAZEdTGQC+27if2Uk7uPfStsS1qO92HGNMFeXLZahniMgyoD+ey0vcoKprHU8W5E6czmLcB6toE1WLP17R3u04xpgqzJdvDbUCTgL/zb9OVbc7GSzYTZm/nl3pp3hv5MWEh4W6HccYU4X50iP4FE9/QIBwIAZYD3R2MFdQS0o9xJs/pnJ7r9YkREe6HccYU8X5MjQUm3/Ze6G4+xxLFOQyMrMZMyeZZvUiGDOwo9txjDFBoMxfQ/FefvqiUjc05+QfX21ky4ETPD00llo1fDlgM8aY8vGlR/BgvsUQoDuwy7FEQWxVWjqvfreF38S3oE/7Rm7HMcYECV8+cuY/lTULT8/gA2fiBK8zWTk8PGclDWtV59FrO7kdxxgTREosBN4Tyeqo6p/8lCdo/XvRZtbtOcbU23pQLyLM7TjGmCBSbI9ARKqpajbQ2495gtL6Pcf45zcbuf7CZgzofJ7bcYwxQaakI4IlePoBK0QkEXgfOJF7p6rOdThbUMjOUcZ8kEyd8DAmXm9DQsYY//OlRxAOHMQzR3Hu+QQKWCGoANO+38rKHUd44eauNKxdw+04xpggVFIhaOz9xtBq/lcAcgX1vMEVJfXACZ77Yj1XXNCYQRc2czuOMSZIlVQIQoHaFCwAuawQlFNOjjL2g2SqVwth0g2xeOb/McYY/yupEOxW1cf9liTIzFiynZ+3HuKZobGcVy/c7TjGmCBW0pnF9hHVITuPnOLpeWv5VbsofhPf0u04xpggV1Ih6O+3FEFEVXlk7ipyFJ4aYkNCxhj3FVsIVPWQP4MEi7nLd7Jow37GDOxAy8iabscxxpiyX3TOnLt9xzJ4/JMU4ls34I6Lo92OY4wxgBUCv3rsozWcyszmmWFxhITYkJAxpnKwQuAn81bt5vM1e/jjFe1p26i223GMMSaPFQI/OHziDI99vJouzetyb582bscxxpgCbOYTP3jikxSOnMzkrbsuolqo1V5jTOVi70oOW7BuH3N/2cl9fdvSqVldt+MYY8xZrBA46FhGJo98uIr2jWtz/+Xt3I5jjDFFskLgoKc+W8feoxk8OyyOGtVC3Y5jjDFFskLgkB82H+Ddn7dzV+8YurVq4HYcY4wplqOFQEQGish6EdkkIuOKuP9BEUkRkWQR+VpEWjuZx19Onsli3AeraN2wJg8N6OB2HGOMKZFjhcA73/HLwNVAJ2C4iBSegusXIF5V44A5wLNO5fGnv32xge2HTvLM0DgiqtuQkDGmcnPyiKAnsElVt6jqGWAWMDj/Bqq6QFVPehd/Alo4mMcvlm8/zLTFW7nlolb0atPQ7TjGGFMqJwtBc2BHvuU077ri3A18VtQdInKviCSJSNL+/fsrMGLFOp2VzZg5yTStG864qzu6HccYY3xSKZrFInIrEA9MKep+VZ2qqvGqGt+oUSP/hiuDl77ZxKZ9x3lySCx1wsPcjmOMMT5x8szinUD+WVdaeNcVICJXAI8Cl6nqaQfzOGrNrnReWbiZId2b069DY7fjGGOMz5w8IlgKtBeRGBGpDtwMJObfQES6Af8BBqnqPgezOCozO4cxc5JpULM6j11XuB9ujDGVm2OFQFWzgNHAfGAt8J6qrhGRx0VkkHezKUBt4H0RWSEiicU8XaU29dstrNl1lCcGd6Z+zepuxzHGmDJx9KJzqjoPmFdo3WP5bl/h5Ov7w6Z9x3jh641c3eU8ro5t6nYcY4wps0rRLA5U2TnKmDnJ1Kweyl8Hd3Y7jjHGnBMrBOXw5g+pLN9+hMeu60TjOuFuxzHGmHNiheAcbT94kinz19O3QyNu7FbS6RHGGFO5WSE4B6rKuLnJhIYIk2+MRcTmHzbGBC4rBOdg1tId/LD5IH++piPN6ke4HccYY8rFCkEZ7U4/xeRP19KrTSTDE1q5HccYY8rNCkEZqCrjP1xNZk4OzwyNIyTEhoSMMYHPCkEZJK7cxdfr9vGnAR1o3bCW23GMMaZCWCHw0YHjp5mYuIauLetzZ+8Yt+MYY0yFsULgowmJazhxOpspw+IItSEhY0wVYoXAB/PX7OHT5N08cHk72jep43YcY4ypUFYISpF+MpPxH63mgqZ1+X3ftm7HMcaYCufoReeqgkmfpnDoxBneGJFAWKjVTWNM1WPvbCVYtGE/7y9LY+SlbejSvJ7bcYwxxhFWCIpx/HQWj8xdRdtGtfhD//ZuxzHGGMfY0FAxnv18HbvSTzHn9xcTHhbqdhxjjHGMHREUYcnWQ7z14zbuuDiaHq0j3Y5jjDGOskJQSEZmNmM/SKZlZARjBnZwO44xxjjOhoYK+fuXG9h64AQz7rmImtXtr8cYU/XZEUE+K3cc4dXvtnBzQkt6t4tyO44xxviFFQKvM1k5jP0gmUZ1avDItRe4HccYY/zGxj68Xlm4iXV7jvHa7fHUDQ9zO47xQWZmJmlpaWRkZLgdxZhKIzw8nBYtWhAW5vv7mBUCYN2eo7z0zSYGd23GFZ2auB3H+CgtLY06deoQHR1t04Uag2fOlIMHD5KWlkZMjO9XSQ76oaGs7BzGzEmmXkQYE67v7HYcUwYZGRk0bNjQioAxXiJCw4YNy3yUHPRHBK9/v5XktHT+ObwbkbWqux3HlJEVAWMKOpf/E0F9RLBl/3Ge/3IDV3ZqwnVxTd2OY4wxrgjaQpCTo4z7YBU1qoUw6YYu9snSBKzU1FS6dOni2PNPnz6dXbt25S3fc889pKSklPt5U1NTeffdd8v9PKdOneKyyy4jOzs7b90//vEPwsPDSU9Pz1s3ffp0Ro8eXeCxffv2JSkpCYDjx48zcuRI2rZtS48ePejbty8///xzubKpKn/4wx9o164dcXFxLF++/Kxtjh07RteuXfN+oqKi+OMf/wjA888/T6dOnYiLi6N///5s27YNgP379zNw4MByZcsvaAvBOz9vY0nqIcZf14kmdcPdjmNMpVW4ELz22mt06tSp3M97LoUgKyvrrHXTpk1jyJAhhIb+75pgM2fOJCEhgblz5/r83Pfccw+RkZFs3LiRZcuW8cYbb3DgwIEy5Svss88+Y+PGjWzcuJGpU6cyatSos7apU6cOK1asyPtp3bo1Q4YMAaBbt24kJSWRnJzMsGHDGDNmDACNGjWiadOmLF68uFz5cgVljyDt8Eme+WwdfdpH8eseLdyOYyrAX/+7hpRdRyv0OTs1q1vqFwjeeecdXnzxRc6cOcNFF13EK6+8wvLly7n77rtZsmQJ2dnZ9OzZk9mzZxMdHc3gwYM5fPgwmZmZTJo0icGDB5OamsrAgQPp1asXP/zwAwkJCdx5551MmDCBffv2MWPGDHr27MnEiRPZvHkzmzZt4sCBA4wZM4bf/e53BfJkZ2czbtw4Fi5cyOnTp7n//vsZOXKkT7kB7r77bpKSkhAR7rrrLlq2bElSUhK33HILERER/Pjjj1x99dU899xzxMfHU7t2bUaNGsW8efNo2rQpkydPZsyYMWzfvp1//OMfDBo0iNTUVG677TZOnDgBwEsvvcQll1zCuHHjWLt2LV27duWOO+5g1KhRjBo1iqSkJKpVq8bzzz9Pv379mD59OnPnzuX48eNkZ2ezaNGiAvsyY8aMAgVl8+bNHD9+nFdeeYUnn3ySO++8s9Tf9ebNm/n555+ZMWMGISGez8cxMTFl+uZNUT7++GNuv/12RIRevXpx5MgRdu/eTdOmRQ9Fb9iwgX379tGnTx8A+vXrl3dfr169eOedd/KWb7jhBmbMmEHv3r3LlRGCsBCoKn+euwoFJt8Ya0NC5pytXbuW2bNns3jxYsLCwrjvvvuYMWMGt99+O4MGDWL8+PGcOnWKW2+9lS5dupCVlcWHH35I3bp1OXDgAL169WLQoEEAbNq0iffff59p06aRkJDAu+++y/fff09iYiKTJ0/mo48+AiA5OZmffvqJEydO0K1bN6699toCmV5//XXq1avH0qVLOX36NL1792bAgAEF3tCKy925c2d27tzJ6tWrAThy5Aj169fnpZdeynvjL+zEiRNcfvnlTJkyhRtvvJHx48fz5ZdfkpKSwh133MGgQYNo3LgxX375JeHh4WzcuJHhw4eTlJTE008/zXPPPccnn3wCwN/+9jdEhFWrVrFu3ToGDBjAhg0bAFi+fDnJyclERha8COSZM2fYsmUL0dHReetmzZrFzTffTJ8+fVi/fj179+6lSZOSvxa+Zs0aunbtWuCoojg33XQT69evP2v9gw8+yO23315g3c6dO2nZsmXecosWLdi5c2exhWDWrFncdNNNRb4vvf7661x99dV5y/Hx8YwfP77UvL4IukIwZ1ka3208wF8HdaZlZE2345gK4sZXf7/++muWLVtGQkIC4Bmrbty4MQCPPfYYCQkJhIeH8+KLLwKeDyGPPPII3377LSEhIezcuZO9e/cCnk+fsbGxAHTu3Jn+/fsjIsTGxpKampr3moMHDyYiIoKIiAj69evHkiVL6Nq1a979X3zxBcnJycyZMweA9PR0Nm7cWKAQFJf7+uuvZ8uWLTzwwANce+21DBgwoNS/g+rVq+eNVcfGxlKjRg3CwsIK5M7MzGT06NGsWLGC0NDQvDf3wr7//nseeOABADp27Ejr1q3ztr3yyivPKgIABw4coH79+gXWzZw5kw8//JCQkBCGDh3K+++/z+jRo4v90FfWD4OzZ88u0/ZlMWvWLN5+++2z1r/zzjskJSUVOBpq3LhxgSG78nC0EIjIQOAFIBR4TVWfLnR/DeAtoAdwELhJVVOdyrPvaAZPfJJCQnQDbuvV2qmXMUFCVbnjjjt46qmnzrrv4MGDHD9+nMzMTDIyMqhVqxYzZsxg//79LFu2jLCwMKKjo/O+712jRo28x4aEhOQth4SEFBgXL/ymVXhZVfnnP//JVVdddU65V65cyfz58/n3v//Ne++9x7Rp00r8OwgLC8vLUFzuv//97zRp0oSVK1eSk5NDeHjZe3K1atUqcn1ERESB78yvWrWKjRs3cuWVVwKeI4aYmBhGjx5Nw4YNOXz4cIHHHzp0iKioKOrXr8/KlSvJzs4u9aigLEcEzZs3Z8eOHXnLaWlpNG/evMjnXblyJVlZWfTo0aPA+q+++oonn3ySRYsWFfh3kpGRQURERIlZfeVYs1hEQoGXgauBTsBwESncYbobOKyq7YC/A884lUdVGf/Rak5n5fDM0DhCQmxIyJRP//79mTNnDvv27QM8byq53+oYOXIkTzzxBLfccgtjx44FPJ/OGzduTFhYGAsWLMjbtiw+/vhjMjIyOHjwIAsXLsz7VJ/rqquu4l//+heZmZmAZ8w5d2y+tNwHDhwgJyeHoUOHMmnSpLxvuNSpU4djx46VOWuu9PR0mjZtSkhICG+//Xbet3sKP2+fPn2YMWNGXu7t27fToUPJl4Jv0KAB2dnZecVg5syZTJw4kdTUVFJTU9m1axe7du1i27ZtJCQksHjxYvbs2QNAUlISp0+fpmXLlrRt25b4+HgmTJiAqgKeZvann3561mvOnj27QHM396dwEQAYNGgQb731FqrKTz/9RL169YodFpo5cybDhw8vsO6XX35h5MiRJCYm5h1t5tqwYUOFfVvMySOCnsAmVd0CICKzgMFA/u+dDQYmem/PAV4SEdHc30QF+nTVbr5I2cu4qzvSplHtin56E4Q6derEpEmTGDBgADk5OYSFhfHyyy+zaNEiwsLC+O1vf0t2djaXXHIJ33zzDbfccgvXX389sbGxxMfH07FjxzK/ZlxcHP369ePAgQP85S9/oVmzZgWGju655x5SU1Pp3r07qkqjRo3y+gul5Y6IiODOO+8kJycHIO+IYcSIEfz+97/PaxaX1X333cfQoUN56623GDhwYN6n+7i4OEJDQ7nwwgsZMWIE9913H6NGjSI2NpZq1aoxffr0Ap+AizNgwAC+//57rrjiCmbNmsW8efMK3H/jjTcya9Ysxo4dywsvvMA111xDTk4OtWvXZubMmXnN4ddee42HHnqIdu3aERERQVRUFFOmTCnz/uZ3zTXXMG/ePNq1a0fNmjV544038u7r2rUrK1asyFt+7733zsr+8MMPc/z4cX79618D0KpVKxITEwFYsGDBWT2ic6aqjvwAw/AMB+Uu3wa8VGib1UCLfMubgaginuteIAlIatWqlZ6Lhev36T1vLtXMrOxzerypfFJSUtyO4FcTJkzQKVOmuB2j0lm2bJneeuutbsfwuz59+uihQ4eKvK+o/xtAkhbzfh0QzWJVnQpMBYiPjz+no4XLzm/EZec3qtBcxhj3de/enX79+vk0vl9V7N+/nwcffJAGDRpUyPM5WQh2Ai3zLbfwritqmzQRqQbUw9M0NsYUMnHiRLcjVFp33XWX2xH8qlGjRtxwww0V9nxOnlm8FGgvIjEiUh24GUgstE0icIf39jDgG+8hjDE+sX8uxhR0Lv8nHCsEqpoFjAbmA2uB91R1jYg8LiKDvJu9DjQUkU3Ag8A4p/KYqic8PJyDBw9aMTDGS73zEZT1K7oSaP+J4uPjNfciUSa42QxlxpytuBnKRGSZqp59ejhBeGaxqTrCwsLKfS0YY0wQX33UGGOMhxUCY4wJclYIjDEmyAVcs1hE9gNlv0iLRxRQvpkmAo/tc3CwfQ4O5dnn1qpa5Fm1AVcIykNEkorrmldVts/BwfY5ODi1zzY0ZIwxQc4KgTHGBLlgKwRT3Q7gAtvn4GD7HBwc2eeg6hEYY4w5W7AdERhjjCnECoExxgS5KlkIRGSgiKwXkU0ictYVTUWkhojM9t7/s4hEuxCzQvmwzw+KSIqIJIvI1yLS2o2cFam0fc633VARUREJ+K8a+rLPIvIb7+96jYi86++MFc2Hf9utRGSBiPzi/fd9jRs5K4qITBORfSKyupj7RURe9P59JItI93K/aHFTlwXqDxCKZ8rLNkB1YCXQqdA29wH/9t6+GZjtdm4/7HM/oKb39qhg2GfvdnWAb4GfgHi3c/vh99we+AVo4F1u7HZuP+zzVGCU93YnINXt3OXc50uB7sDqYu6/BvgMEKAX8HN5X7MqHhH0BDap6hZVPQPMAgYX2mYw8Kb39hygv4iIHzNWtFL3WVUXqOpJ7+JPeGaMC2S+/J4BngCeAarCtap92effAS+r6mEAVd3n54wVzZd9VqCu93Y9YJcf81U4Vf0WOFTCJoOBt9TjJ6C+iDQtz2tWxULQHNiRbznNu67IbdQzgU460NAv6Zzhyz7ndzeeTxSBrNR99h4yt1TVT/0ZzEG+/J7PB84XkcUi8pOIDPRbOmf4ss8TgVtFJA2YBzzgn2iuKev/91LZfARBRkRuBeKBy9zO4iQRCQGeB0a4HMXfquEZHuqL56jvWxGJVdUjboZy2HBguqr+TUQuBt4WkS6qmuN2sEBRFY8IdgIt8y238K4rchsRqYbncPKgX9I5w5d9RkSuAB4FBqnqaT9lc0pp+1wH6AIsFJFUPGOpiQHeMPbl95wGJKpqpqpuBTbgKQyBypd9vht4D0BVfwTC8Vycrary6f97WVTFQrAUaC8iMSJSHU8zOLHQNonAHd7bw4Bv1NuFCVCl7rOIdAP+g6cIBPq4MZSyz6qarqpRqhqtqtF4+iKDVDWQ5zn15d/2R3iOBhCRKDxDRVv8mLGi+bLP24H+ACJyAZ5CsN+vKf0rEbjd++2hXkC6qu4uzxNWuaEhVc0SkdHAfDzfOJimqmtE5HEgSVUTgdfxHD5uwtOUudm9xOXn4z5PAWoD73v74ttVdZBrocvJx32uUnzc5/nAABFJAbKBh1U1YI92fdznh4BXReT/4WkcjwjkD3YiMhNPMY/y9j0mAGEAqvpvPH2Qa4BNwEngznK/ZgD/fRljjKkAVXFoyBhjTBlYITDGmCBnhcAYY4KcFQJjjAlyVgiMMSbIWSEwlZKIZIvIinw/0SVse7wCXm+6iGz1vtZy7xmqZX2O10Skk/f2I4Xu+6G8Gb3Pk/v3slpE/isi9UvZvmugX43TOM++PmoqJRE5rqq1K3rbEp5jOvCJqs4RkQHAc6oaV47nK3em0p5XRN4ENqjqkyVsPwLPVVdHV3QWU3XYEYEJCCJS2zuPwnIRWSUiZ11pVESaisi3+T4x9/GuHyAiP3of+76IlPYG/S3QzvvYB73PtVpE/uhdV0tEPhWRld71N3nXLxSReBF5Gojw5pjhve+4989ZInJtvszTRWSYiISKyBQRWeq9xvxIH/5afsR7sTER6endx19E5AcR6eA9E/dx4CZvlpu82aeJyBLvtkVdsdUEG7evvW0/9lPUD56zYld4fz7EcxZ8Xe99UXjOqsw9oj3u/fMh4FHv7VA81xuKwvPGXsu7fizwWBGvNx0Y5r39a+BnoAewCqiF56zsNUA3YCjwar7H1vP+uRDvnAe5mfJtk5vxRuBN7+3qeK4iGQHcC4z3rq8BJAExReQ8nm//3gcGepfrAtW8t68APvDeHgG8lO/xk4Fbvbfr47kWUS23f9/24+5PlbvEhKkyTqlq19wFEQkDJovIpUAOnk/CTYA9+R6zFJjm3fYjVV0hIpfhmaxksffSGtXxfJIuyhQRGY/nOjV347l+zYeqesKbYS7QB/gc+JuIPINnOOm7MuzXZ8ALIlIDGAh8q6qnvMNRcSIyzLtdPTwXi9ta6PERIrLCu/9rgS/zbf+miLTHc5mFsGJefwAwSET+5F0OB1p5n8sEKSsEJlDcAjQCeqhqpniuKBqefwNV/dZbKK4FpovI88Bh4EtVHe7DazysqnNyF0Skf1EbqeoG8cx1cA0wSUS+VtXHfdkJVc0QkYXAVcBNeCZaAc9sUw+o6vxSnuKUqnYVkZp4rr9zP/Aingl4Fqjqjd7G+sJiHi/AUFVd70teExysR2ACRT1gn7cI9APOmnNZPPMw71XVV4HX8Ez39xPQW0Ryx/xricj5Pr7md8ANIlJTRGrhGdb5TkSaASdV9R08F/Mras7YTO+RSVFm47lQWO7RBXje1EflPkZEzve+ZpHUM9vcH4CH5H+XUs+9FPGIfJsewzNElms+8IB4D4/Ec1VaE+SsEJhAMQOIF5FVwO3AuiK26QusFJFf8HzafkFV9+N5Y5wpIsl4hoU6+vKCqrocT+9gCZ6ewWuq+gsQCyzxDtFMACYV8fCpQHJus7iQL/BMDPSVeqZfBE/hSgGWi2fS8v9QyhG7N0synolZngWe8u57/sctADrlNovxHDmEebOt8S6bIGdfHzXGmCBnRwTGGBPkrBAYY0yQs0JgjDFBzgqBMcYEOSsExhgT5KwQGGNMkLNCYIwxQe7/A3CX2nt5i/GOAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "fpr, tpr, thresholds = roc_curve(y_predicted, y_test_smoted)\n",
    "roc_auc = auc(fpr, tpr)\n",
    "display = RocCurveDisplay(\n",
    "    fpr=fpr, tpr=tpr, roc_auc=roc_auc, estimator_name='example estimator')\n",
    "display.plot()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.2"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
